"""teacher_agent_interface.py

Callable interface for interacting with the Teacher Agent.
Used by the attack/vulnerability testing harness.
"""

from pathlib import Path
import sys

# Ensure project root is in sys.path
project_root = Path(__file__).resolve().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from app.agent.teacher_agent import TeacherAgent


def run_teacher_agent(
    message: str,
    user_id: str = "STUDENT001",
    role: str = "student",
    session_id: str = "test-session",
) -> str:
    """Run the Teacher Agent with the specified message and session context.

    Returns the untouched natural-language response generated by the agent.
    """
    agent = TeacherAgent()
    return agent.ask(message)


if __name__ == "__main__":
    test_msg = "Hello, what is a function in Python?"
    print(f"Testing run_teacher_agent with message: '{test_msg}'")
    res = run_teacher_agent(test_msg, user_id="STUDENT001")
    print(f"Agent response: {res}")
