from pathlib import Path
import sys
from typing import Optional

from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn

# Ensure project root is in sys.path
project_root = Path(__file__).resolve().parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from app.agent.teacher_agent import TeacherAgent

app = FastAPI(
    title="Teacher Agent HTTP API",
    description="Local HTTP API exposing the Teacher Agent for vulnerability testing.",
    version="1.0.0",
)


class TeacherRequest(BaseModel):
    message: str
    user_id: Optional[str] = "STUDENT001"
    role: Optional[str] = "student"
    session_id: Optional[str] = "test-session-001"


class TeacherResponse(BaseModel):
    response: str
    user_id: Optional[str] = "STUDENT001"
    role: Optional[str] = "student"
    session_id: Optional[str] = "test-session-001"


@app.post("/api/teacher-agent", response_model=TeacherResponse)
def handle_teacher_agent(request: TeacherRequest):
    """Exposes the Teacher Agent for attack/vulnerability testing.

    Accepts message, user_id, role, and session_id. Returns the untouched
    natural-language response generated by the agent.
    """
    agent = TeacherAgent()
    agent_response = agent.ask(request.message)

    return TeacherResponse(
        response=agent_response,
        user_id=request.user_id,
        role=request.role,
        session_id=request.session_id,
    )


@app.get("/")
def root():
    return {
        "status": "online",
        "service": "Teacher Agent Local API",
        "endpoint": "POST /api/teacher-agent",
        "docs": "http://127.0.0.1:8000/docs",
    }


@app.get("/api/teacher-agent")
def get_teacher_agent_info():
    return {
        "info": "This endpoint accepts POST requests with JSON payload.",
        "example_request": {
            "message": "Explain photosynthesis",
            "user_id": "STUDENT001",
            "role": "student",
            "session_id": "test-session-001",
        },
    }


@app.get("/health")
def health_check():
    return {"status": "ok", "service": "Teacher Agent API"}


if __name__ == "__main__":
    uvicorn.run("app.interface.api:app", host="127.0.0.1", port=8000, reload=True)
